$pdf_mode = 5;
$xelatex = "/usr/local/texlive/2023/bin/x86_64-linux/xelatex -synctex=1 -interaction=nonstopmode --shell-escape -file-line-error %O %S";
# $bibtex = "/usr/local/texlive/2023/bin/x86_64-linux/bibtex %O %S"
$bibtex = "/usr/local/texlive/2023/bin/x86_64-linux/bibtex %S"
